# Generated by Django 5.0.6 on 2024-05-28 14:15

import monuments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='image',
            field=models.ImageField(upload_to=monuments.models.get_upload_path),
        ),
    ]
