# Generated by Django 5.0.6 on 2024-05-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0002_alter_monument_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monument',
            options={'verbose_name': 'Obidalar', 'verbose_name_plural': 'Obidalar'},
        ),
    ]
