# Generated by Django 5.0.6 on 2024-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0003_alter_monument_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monument',
            options={'verbose_name': 'Obida', 'verbose_name_plural': 'Obidalar'},
        ),
        migrations.AddField(
            model_name='monument',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
