# Generated by Django 5.0.6 on 2024-06-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0004_alter_monument_options_monument_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='description',
        ),
        migrations.AddField(
            model_name='monument',
            name='description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
