# Generated by Django 5.0.6 on 2024-06-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Shaharlar', 'verbose_name_plural': 'Shaharlar'},
        ),
    ]
