# Generated by Django 5.0.6 on 2024-05-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Sevimlilar', 'verbose_name_plural': 'Sevimlilar'},
        ),
    ]
